name: streamlit
channels:
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - ca-certificates=2022.3.18
  - certifi=2021.10.8
  - cycler=0.11.0
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - intel-openmp=2021.4.0
  - joblib=1.1.0
  - jpeg=9d
  - kiwisolver=1.3.1
  - lcms2=2.12
  - libcxx=12.0.0
  - libffi=3.3
  - libgfortran=3.0.1
  - libpng=1.6.37
  - libtiff=4.2.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - llvm-openmp=12.0.0
  - lz4-c=1.9.3
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - numexpr=2.8.1
  - numpy-base=1.21.2
  - olefile=0.46
  - openssl=1.1.1n
  - packaging=21.3
  - pip=21.2.4
  - plotly=5.6.0
  - python=3.9.7
  - python-dateutil=2.8.2
  - readline=8.1.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.37.0
  - tenacity=8.0.1
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - tornado=6.1
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - altair==4.2.0
    - appnope==0.1.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - astor==0.8.1
    - asttokens==2.0.5
    - attrs==21.4.0
    - backcall==0.2.0
    - base58==2.1.1
    - black==21.12b0
    - bleach==4.1.0
    - blinker==1.4
    - cachetools==5.0.0
    - cffi==1.15.0
    - charset-normalizer==2.0.10
    - click==8.0.3
    - debugpy==1.5.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - entrypoints==0.3
    - executing==0.8.2
    - gitdb==4.0.9
    - gitpython==3.1.26
    - idna==3.3
    - ipykernel==6.7.0
    - ipython==8.0.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jedi==0.18.1
    - jinja2==3.0.3
    - jsonschema==4.4.0
    - jupyter-client==7.1.1
    - jupyter-core==4.9.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2
    - lxml==4.8.0
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - multitasking==0.0.10
    - mypy-extensions==0.4.3
    - nbclient==0.5.10
    - nbconvert==6.4.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.4
    - notebook==6.4.7
    - numpy==1.22.1
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathspec==0.9.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.0.0
    - platformdirs==2.4.1
    - prometheus-client==0.12.0
    - prompt-toolkit==3.0.24
    - protobuf==3.19.3
    - ptyprocess==0.7.0
    - pure-eval==0.2.1
    - pyarrow==6.0.1
    - pycparser==2.21
    - pydeck==0.7.1
    - pygments==2.11.2
    - pympler==1.0.1
    - pyparsing==3.0.6
    - pyrsistent==0.18.1
    - pytz==2021.3
    - pytz-deprecation-shim==0.1.0.post0
    - pyzmq==22.3.0
    - requests==2.27.1
    - send2trash==1.8.0
    - smmap==5.0.0
    - stack-data==0.1.4
    - streamlit==1.4.0
    - streamlit-yellowbrick==0.0.3
    - terminado==0.12.1
    - testpath==0.5.0
    - toml==0.10.2
    - tomli==1.2.3
    - toolz==0.11.2
    - traitlets==5.1.1
    - typing-extensions==4.0.1
    - tzdata==2021.5
    - tzlocal==4.1
    - urllib3==1.26.8
    - validators==0.18.2
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.2
    - yellowbrick==1.4
    - yfinance==0.1.70
